export * from './data';
export { isPair } from './isPair';
export { calcMedian } from './calcMedian';
export { calcPromedy } from './calcPromedy';
export { medianByPerson } from './medianByPerson';
export { generalMedianOfPersons } from './generalMedianOfPersons';
export { calcPercentualProjection } from './calcPercentualProjection';
export { projectionByPerson } from './projectionByPerson';
export { projectionByCompany } from './projectionByCompany';
export { tops } from './tops';